CREATE DATABASE STUDENT_DATA;
USE STUDENT_DATA;
 SELECT * FROM `STUDENT MENTAL HEALTH`;
RENAME TABLE `STUDENT MENTAL HEALTH` TO STUDENT_MENTAL_HEALTH;
SELECT * FROM STUDENT_LIFESTYLE_DATASET;

-- 1. WHAT IS THE AVERAGE CGPA GROUPED BY STRESS LEVEL
SELECT STRESS_LEVEL,ROUND(AVG(`WHAT IS YOUR CGPA?`),2)AS AVG_CGPA
FROM STUDENT_MENTAL_HEALTH M JOIN STUDENT_LIFESTYLE_DATASET L ON M.STUDENT_ID = L.STUDENT_ID
GROUP BY STRESS_LEVEL;

-- 2. HOW MANY STUDENTS FROM EACH COURSE REPORT HAVING DEPRESSION AND ANXIETY
SELECT `WHAT IS YOUR COURSE?`,
COUNT(CASE WHEN `DO YOU HAVE DEPRESSION?` ="YES" THEN 1 END) AS DEPRESSION_COUNT,
COUNT(CASE WHEN `DO YOU HAVE ANXIETY?` ="YES" THEN 1 END) AS ANXIETY_COUNT
FROM STUDENT_MENTAL_HEALTH
GROUP BY `WHAT IS YOUR COURSE?`
ORDER BY DEPRESSION_COUNT DESC , ANXIETY_COUNT DESC;

-- 3. LIST STUDENTS WHO STUDY LESS THAN 8 HOURS AND HAVE HIGH STRESS
SELECT STUDENT_ID,SLEEP_HOURS_PER_DAY, STRESS_LEVEL
FROM STUDENT_LIFESTYLE_DATASET
WHERE SLEEP_HOURS_PER_DAY < 8 AND STRESS_LEVEL="HIGH"
ORDER BY SLEEP_HOURS_PER_DAY;

-- 4. FIND TOP 5 STUDENTS WITH THE LOWEST SLEEP HOURS BUT HIGHEST CGPA
SELECT L.STUDENT_ID, L.SLEEP_HOURS_PER_DAY, M.`WHAT IS YOUR CGPA?`
FROM STUDENT_LIFESTYLE_DATASET L JOIN STUDENT_MENTAL_HEALTH M ON L.STUDENT_ID = M.STUDENT_ID
ORDER BY L.SLEEP_HOURS_PER_DAY ASC , M.`WHAT IS YOUR CGPA?` DESC
LIMIT 5;

-- 5. WHAT IS THE DISTRIBUTION OF PANIC ATTACKS ACROSS DIFFERENT YEARS OF STUDY
SELECT `Your current year of Study`, COUNT(*) AS TOTAL_WITH_PANIC
FROM STUDENT_MENTAL_HEALTH
GROUP BY `Your current year of Study` ;

-- 6. WHAT PERCENTAGE OF OVERALL STUDENTS REPORTED HAVING DEPRESSION
SELECT COUNT(*) AS TOTAL_STUDENTS,COUNT(CASE WHEN `Do you have Depression?` ="YES" THEN 1 END) AS TOTAL_WITH_DEPRESSION,
ROUND(100 * COUNT(CASE WHEN `Do you have Depression?` ="YES" THEN 1 END)/COUNT(*),2) AS TOTAL_PERCENTAGE
FROM STUDENT_MENTAL_HEALTH;

-- 7. WHAT IS THE CORRELATION BETWEEN PHYSICAL ACTIVITY AND STRESS
SELECT STRESS_LEVEL, ROUND(AVG(PHYSICAL_ACTIVITY_HOURS_PER_DAY),2) AS AVG_ACTIVITY_HOUR
FROM STUDENT_LIFESTYLE_DATASET
GROUP BY STRESS_LEVEL
ORDER BY AVG_ACTIVITY_HOUR DESC;

-- 8. AMONG MARRIED VS UNMARRIED STUDENTS WHO IS MORE LIKELY TO SEEK TREATMENT
SELECT `Marital status`,
COUNT(CASE WHEN `Did you seek any specialist for a treatment?` ="YES" THEN 1 END) AS TREATMENT_COUNT
FROM STUDENT_MENTAL_HEALTH
GROUP BY `Marital status`;

-- 9. WHICH GENDER TENDS TO REPORT HIGHER STRESS LEVELS ON AVERAGE
SELECT M.`CHOOSE YOUR GENDER`, 
AVG(CASE
 WHEN L.STRESS_LEVEL = "HIGH" THEN 1 
WHEN L.STRESS_LEVEL = "MODERATE" THEN 0.5  
ELSE 0 END) AS AVG_STRESS_SCORE
FROM STUDENT_MENTAL_HEALTH M JOIN STUDENT_LIFESTYLE_DATASET L ON M.STUDENT_ID = L.STUDENT_ID
GROUP BY M.`CHOOSE YOUR GENDER`;

-- 10. CREATE A CTE TO FIND STUDENTS WITH BOTH DEPRESSION AND HIGH STRESS
WITH DEPRESSED_STRESSED  AS (
	SELECT M.STUDENT_ID, M.`WHAT IS YOUR COURSE?`, M.`DO YOU HAVE DEPRESSION?`, L.STRESS_LEVEL
    FROM STUDENT_MENTAL_HEALTH M JOIN STUDENT_LIFESTYLE_DATASET L ON M.STUDENT_ID = L.STUDENT_ID
    WHERE M.`DO YOU HAVE DEPRESSION?` = "YES" AND L.STRESS_LEVEL ="HIGH"
)
SELECT * FROM DEPRESSED_STRESSED;

-- 11. WHO SPENDS THE MOST TIME ON SOCIAL HOURS 
SELECT STUDENT_ID, SOCIAL_HOURS_PER_DAY, 
RANK() OVER (ORDER BY SOCIAL_HOURS_PER_DAY DESC) AS SOCIAL_RANK
FROM STUDENT_LIFESTYLE_DATASET;

-- 12. WHAT IS THE AVERAGE SOCIAL TIME FOR STUDENTS WHO HAVE PANIC ATTACKS
SELECT M.STUDENT_ID, L.SOCIAL_HOURS_PER_DAY, M.`DO YOU HAVE PANIC ATTACK?`,
ROUND(AVG(L.SOCIAL_HOURS_PER_DAY) OVER(PARTITION BY M.`DO YOU HAVE PANIC ATTACK?`),2) AS AVG_SOCIAL_BY_GROUP
FROM STUDENT_MENTAL_HEALTH M JOIN STUDENT_LIFESTYLE_DATASET L ON M.STUDENT_ID = L.STUDENT_ID 
ORDER BY L.SOCIAL_HOURS_PER_DAY DESC;






